# Generated by Django 5.2.3 on 2025-07-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile_country_profile_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_block_user", "Can block user"),
                    ("can_view_client", "CCan viewc lient"),
                    ("can_disable_mailing", "Can disable mailing"),
                    ("can_view_mailing", "Can view mailing"),
                    ("can_disable_message", "Can disable message"),
                    ("can_view_message", "Can view message"),
                    ("can_view_all", "Can view all items"),
                    ("is_manager", "Has manager privileges"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
