# Generated by Django 5.2.3 on 2025-07-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_block_user", "Может блокировать пользователей"),
                    ("can_view_all", "Может просматривать все объекты"),
                    ("can_finish_mailing", "Может завершать рассылки"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(default=False, verbose_name="Заблокирован"),
        ),
    ]
