# Generated by Django 5.2.3 on 2025-07-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_alter_client_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время окончания рассылки"
            ),
        ),
    ]
