# Generated by Django 5.2.3 on 2025-07-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_alter_mailing_end_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_mailing", "Can view mailing"),
                    ("can_disable_mailing", "Can disable mailing"),
                    ("can_view_all_mailings", "Can view all mailings"),
                    ("can_view_user_stats", "Can view users statistics"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
