# Generated by Django 5.2.3 on 2025-07-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0004_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Запущена"),
                    ("completed", "Завершена"),
                ],
                default="created",
                max_length=100,
                verbose_name="Статус",
            ),
        ),
    ]
