# Generated by Django 5.2.3 on 2025-07-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="frequency",
            field=models.CharField(
                default="weekly", max_length=100, verbose_name="Периодичность"
            ),
        ),
    ]
