# Generated by Django 5.2.3 on 2025-07-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0007_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_block_user", "Can block users"),
                    ("can_view_all", "Can view all mailings"),
                    ("can_finish_mailing", "Can finish any mailing"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
